### ISSUE TITLE
Doesn't work with Flatpak installed apps that used libadwaita.

### ISSUE THREAD

**Issue by hrqmonteiro** [odziom91/libadwaita-themes#4]
Like BlackBox, for example:

![Screenshot from 2022-08-07 11-45-03](https://user-images.githubusercontent.com/17055027/183296740-c594cd6d-1776-43ff-a6b0-17b0319164a3.png)

**Comment by orowith2os** [comment]
Gradience will automatically set Flatpak permissions to allow for theming, set the permissions for global (aka all apps) as follows:

`xdg-config/gtk-4.0:ro`
`xdg-config/gtk-3.0:ro`

This can be done via Flatseal.
